apiVersion: apps/v1
kind: Deployment
metadata:
  name: lofy-client-dev
  namespace: lofy-client
spec:
  selector:
    matchLabels:
      app: react-client-dev
  replicas: 3  
  strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
  template:
    metadata:
      labels:
        app: react-client-dev
    spec:
      containers:
        - name: react-client-dev
          image: CONTAINER_IMAGE
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 80
